import { TarotCard } from "@/types/tarot";

/**
 * 타로 카드 데이터셋 (22장 메이저 아르카나 중 12장)
 * 모든 해석은 오락 목적이며, 결정적 표현을 피합니다.
 */
export const tarotCards: TarotCard[] = [
  {
    id: 0,
    name: "The Fool",
    nameKo: "바보",
    emoji: "🃏",
    keywords: ["새로운 시작", "모험", "순수"],
    shortReading: "새로운 시작의 에너지가 느껴지는 하루입니다. 가벼운 마음으로 첫 발을 내딛어 보세요.",
    detailedReading: "오늘은 마치 아무것도 모르는 듯한 순수한 마음이 오히려 큰 힘이 될 수 있는 날입니다. 너무 많은 것을 계산하기보다, 직관을 따라 움직여 보는 것도 좋겠습니다. 새로운 만남이나 기회가 다가올 수 있으니, 열린 마음을 유지해 보세요. 다만, 지나친 무모함은 주의가 필요할 수 있습니다.",
    advice: "오늘은 '시작'에 집중해 보세요. 작은 것이라도 좋습니다.",
    luckyColor: "노란색",
    luckyNumber: 0,
  },
  {
    id: 1,
    name: "The Magician",
    nameKo: "마법사",
    emoji: "✨",
    keywords: ["창조력", "의지", "집중"],
    shortReading: "당신 안에 있는 능력을 발휘할 수 있는 날입니다. 자신감을 가져 보세요.",
    detailedReading: "마법사 카드는 당신이 가진 재능과 자원을 잘 활용할 수 있는 시기를 암시합니다. 오늘 하루, 무언가를 만들어 내거나 기획하는 일에 좋은 에너지가 흐를 수 있습니다. 커뮤니케이션도 원활할 수 있으니, 중요한 대화가 있다면 오늘 시도해 보는 것도 좋겠습니다.",
    advice: "집중하면 놀라운 결과를 만들어 낼 수 있을지도 모릅니다.",
    luckyColor: "빨간색",
    luckyNumber: 1,
  },
  {
    id: 2,
    name: "The High Priestess",
    nameKo: "여사제",
    emoji: "🌙",
    keywords: ["직관", "내면", "신비"],
    shortReading: "조용히 내면의 목소리에 귀 기울여 보세요. 답은 이미 안에 있을 수 있습니다.",
    detailedReading: "여사제 카드는 깊은 직관과 내면의 지혜를 상징합니다. 오늘은 외부의 소음보다 자신의 느낌을 더 신뢰해 보는 것이 좋겠습니다. 꿈이나 갑자기 떠오르는 생각에 주의를 기울여 보세요. 조용한 시간을 갖는 것이 큰 도움이 될 수 있습니다.",
    advice: "명상이나 조용한 산책으로 마음을 가라앉혀 보세요.",
    luckyColor: "남색",
    luckyNumber: 2,
  },
  {
    id: 3,
    name: "The Empress",
    nameKo: "여황제",
    emoji: "🌸",
    keywords: ["풍요", "아름다움", "사랑"],
    shortReading: "따뜻하고 풍요로운 에너지가 감싸는 하루가 될 수 있습니다.",
    detailedReading: "여황제는 풍요와 사랑의 에너지를 나타냅니다. 오늘은 주변 사람들과의 관계에서 따뜻함을 느낄 수 있는 날입니다. 자신을 위한 작은 사치나 즐거움을 허락해 보세요. 창작 활동에도 좋은 에너지가 흐를 수 있습니다.",
    advice: "자신과 주변 사람들에게 따뜻한 말 한마디를 건네 보세요.",
    luckyColor: "분홍색",
    luckyNumber: 3,
  },
  {
    id: 4,
    name: "The Emperor",
    nameKo: "황제",
    emoji: "👑",
    keywords: ["안정", "리더십", "구조"],
    shortReading: "체계적으로 접근하면 좋은 결과를 기대해 볼 수 있는 날입니다.",
    detailedReading: "황제 카드는 질서와 구조의 중요성을 강조합니다. 오늘은 계획을 세우고 체계적으로 일을 진행하면 효율적인 하루를 보낼 수 있을 것입니다. 리더십이 필요한 상황에서 당신의 능력이 빛날 수 있습니다.",
    advice: "오늘의 할 일 목록을 만들어 하나씩 해결해 보세요.",
    luckyColor: "금색",
    luckyNumber: 4,
  },
  {
    id: 5,
    name: "The Lovers",
    nameKo: "연인",
    emoji: "💕",
    keywords: ["선택", "조화", "사랑"],
    shortReading: "중요한 선택의 순간이 올 수 있습니다. 마음의 소리를 따라가 보세요.",
    detailedReading: "연인 카드는 단순한 로맨스뿐 아니라 중요한 선택과 가치관의 조화를 의미합니다. 오늘 어떤 결정을 내려야 한다면, 머리보다 마음이 이끄는 방향을 고려해 보세요. 관계에서 진솔한 소통이 큰 도움이 될 수 있습니다.",
    advice: "진심을 담아 대화해 보세요. 뜻밖의 연결이 생길 수 있습니다.",
    luckyColor: "주황색",
    luckyNumber: 6,
  },
  {
    id: 6,
    name: "The Chariot",
    nameKo: "전차",
    emoji: "🏎️",
    keywords: ["전진", "의지력", "승리"],
    shortReading: "강한 의지로 앞으로 나아갈 수 있는 하루입니다. 멈추지 마세요.",
    detailedReading: "전차 카드는 결단력과 추진력을 상징합니다. 오늘은 목표를 향해 힘차게 나아가는 것이 좋겠습니다. 어려움이 있더라도 포기하지 않으면 좋은 방향으로 흘러갈 가능성이 있습니다. 다만, 지나친 고집은 부딪힘을 만들 수 있으니 유연함도 함께 가져 보세요.",
    advice: "목표를 하나 정하고 오늘 하루 집중해 보세요.",
    luckyColor: "파란색",
    luckyNumber: 7,
  },
  {
    id: 7,
    name: "Strength",
    nameKo: "힘",
    emoji: "🦁",
    keywords: ["용기", "인내", "내면의 힘"],
    shortReading: "부드러운 강인함이 필요한 날입니다. 당신은 충분히 강합니다.",
    detailedReading: "힘 카드는 물리적 힘이 아닌 내면의 용기와 인내를 나타냅니다. 오늘 어려운 상황이 닥치더라도, 조용하고 차분하게 대처하면 좋은 결과를 기대해 볼 수 있습니다. 자신의 감정을 억누르기보다 부드럽게 받아들이는 것이 중요합니다.",
    advice: "힘든 순간에도 깊은 호흡으로 마음을 다잡아 보세요.",
    luckyColor: "초록색",
    luckyNumber: 8,
  },
  {
    id: 8,
    name: "The Wheel of Fortune",
    nameKo: "운명의 수레바퀴",
    emoji: "🎡",
    keywords: ["변화", "순환", "행운"],
    shortReading: "변화의 바람이 불어올 수 있는 날입니다. 흐름에 맡겨 보세요.",
    detailedReading: "운명의 수레바퀴는 삶의 순환과 변화를 상징합니다. 오늘은 예상치 못한 변화가 생길 수 있지만, 그것이 반드시 나쁜 것만은 아닐 수 있습니다. 새로운 기회가 찾아올 수도 있으니, 변화를 두려워하기보다 유연하게 받아들여 보세요.",
    advice: "변화를 기회로 바라보는 시선을 가져 보세요.",
    luckyColor: "보라색",
    luckyNumber: 10,
  },
  {
    id: 9,
    name: "The Star",
    nameKo: "별",
    emoji: "⭐",
    keywords: ["희망", "영감", "치유"],
    shortReading: "희망의 빛이 비추는 하루입니다. 좋은 일이 다가오고 있을지도 모릅니다.",
    detailedReading: "별 카드는 고난 후에 찾아오는 평화와 희망을 의미합니다. 최근 힘든 시간을 보냈다면, 오늘부터 서서히 회복의 에너지를 느낄 수 있을 것입니다. 영감이 풍부한 날이기도 하니, 창작이나 새로운 아이디어를 메모해 두는 것도 좋겠습니다.",
    advice: "밤하늘의 별을 바라보며 소원을 빌어 보세요.",
    luckyColor: "하늘색",
    luckyNumber: 17,
  },
  {
    id: 10,
    name: "The Moon",
    nameKo: "달",
    emoji: "🌕",
    keywords: ["환상", "불안", "잠재의식"],
    shortReading: "불확실한 감정이 느껴질 수 있습니다. 서두르지 말고 기다려 보세요.",
    detailedReading: "달 카드는 불안이나 혼란을 나타내기도 하지만, 동시에 깊은 감성과 창의력을 암시합니다. 오늘은 모든 것이 명확하게 보이지 않을 수 있지만, 그것이 자연스러운 과정일 수 있습니다. 중요한 결정은 조금 미루고, 감정을 충분히 느낀 뒤 행동하는 것이 좋겠습니다.",
    advice: "불안할 때는 일기를 쓰거나 감정을 정리해 보세요.",
    luckyColor: "은색",
    luckyNumber: 18,
  },
  {
    id: 11,
    name: "The Sun",
    nameKo: "태양",
    emoji: "☀️",
    keywords: ["기쁨", "성공", "활력"],
    shortReading: "밝고 활기찬 에너지가 넘치는 날입니다! 자신감을 가지세요.",
    detailedReading: "태양 카드는 가장 긍정적인 카드 중 하나입니다. 오늘은 밝은 에너지와 함께 좋은 소식이 찾아올 수 있습니다. 사람들과의 교류가 즐겁고, 하는 일마다 순조로울 가능성이 있습니다. 이 좋은 에너지를 주변 사람들과 나눠 보세요.",
    advice: "오늘의 좋은 기운을 소중한 사람들과 함께하세요.",
    luckyColor: "노란색",
    luckyNumber: 19,
  },
];
