import type { TarotCard } from '@/types/tarot';

/**
 * 마이너 아르카나 56장: 완드·컵·검·펜타클 각 14장 (에이스~10, 시종·기사·여왕·왕).
 * id 22~77. imageUrl: 로컬 /tarot/22.jpg~77.jpg (RWS 퍼블릭 도메인).
 * 카피 톤: 오락 목적, 가능성·암시 유지.
 */
const W = 'Wands';
const C = 'Cups';
const S = 'Swords';
const P = 'Pentacles';

const minorArcanaCardsBase: TarotCard[] = [
  // 완드 (22~35): 에너지·의지·창조
  { id: 22, name: `Ace of ${W}`, nameKo: '완드의 에이스', emoji: '🪄', keywords: ['새 시작', '영감', '에너지'], shortReading: '새로운 도전이나 창의적인 시작의 에너지가 느껴질 수 있습니다.', detailedReading: '완드 에이스는 새로운 동기나 영감을 상징합니다. 오늘은 하고 싶은 일을 시작해 보거나, 머릿속 아이디어를 한 가지라도 적어 보는 것이 좋겠습니다.', advice: '오늘 한 가지 새로운 것을 시작해 보세요.', luckyColor: '빨간색', luckyNumber: 1 },
  { id: 23, name: `Two of ${W}`, nameKo: '완드의 2', emoji: '🪄', keywords: ['계획', '결단', '방향'], shortReading: '앞으로의 방향을 정하거나 계획을 세워 보는 하루가 될 수 있습니다.', detailedReading: '완드 2는 계획과 선택을 상징합니다. 여러 가능성 중 하나를 골라 보거나, 목표를 구체화해 보는 것이 도움이 될 수 있습니다.', advice: '오늘 할 일 중 하나를 골라 끝까지 해 보세요.', luckyColor: '주황색', luckyNumber: 2 },
  { id: 24, name: `Three of ${W}`, nameKo: '완드의 3', emoji: '🪄', keywords: ['협력', '확장', '성장'], shortReading: '다른 사람과 함께하거나 영역을 넓혀 보는 에너지가 있을 수 있습니다.', detailedReading: '완드 3는 협력과 확장을 상징합니다. 혼자보다 함께할 때 더 잘 풀릴 수 있는 일이 있다면 오늘 연락해 보세요.', advice: '함께할 사람 한 명을 떠올리고 연락해 보세요.', luckyColor: '노란색', luckyNumber: 3 },
  { id: 25, name: `Four of ${W}`, nameKo: '완드의 4', emoji: '🪄', keywords: ['축하', '안정', '휴식'], shortReading: '작은 성취를 축하하고 잠시 쉬어 보는 하루가 좋겠습니다.', detailedReading: '완드 4는 안정과 축하를 상징합니다. 지금까지의 노력을 인정하고 휴식을 취해 보는 것도 좋습니다.', advice: '오늘은 완료한 일을 하나만 골라 스스로 칭찬해 보세요.', luckyColor: '초록색', luckyNumber: 4 },
  { id: 26, name: `Five of ${W}`, nameKo: '완드의 5', emoji: '🪄', keywords: ['경쟁', '도전', '불협화'], shortReading: '작은 마찰이나 경쟁이 있어도 당황하지 말고 차분히 대처해 보세요.', detailedReading: '완드 5는 경쟁이나 의견 차이를 상징합니다. 감정이 올라와도 한숨 돌리고 말을 조절해 보는 것이 좋겠습니다.', advice: '오늘은 논쟁보다 공통점을 찾아 보세요.', luckyColor: '주황색', luckyNumber: 5 },
  { id: 27, name: `Six of ${W}`, nameKo: '완드의 6', emoji: '🪄', keywords: ['승리', '자신감', '인정'], shortReading: '노력이 인정되거나 작은 승리를 느낄 수 있는 날입니다.', detailedReading: '완드 6는 승리와 인정을 상징합니다. 당신의 능력이 빛을 보는 상황이 올 수 있으니 자신감을 가져 보세요.', advice: '오늘 잘한 일 하나를 떠올려 보세요.', luckyColor: '빨간색', luckyNumber: 6 },
  { id: 28, name: `Seven of ${W}`, nameKo: '완드의 7', emoji: '🪄', keywords: ['방어', '인내', '고수'], shortReading: '위치를 지키거나 조금만 더 버티는 것이 좋은 하루일 수 있습니다.', detailedReading: '완드 7은 방어와 인내를 상징합니다. 쉽게 포기하지 않고 한 번 더 시도해 보는 것이 좋겠습니다.', advice: '오늘은 한 번 더 버티는 날로 삼아 보세요.', luckyColor: '노란색', luckyNumber: 7 },
  { id: 29, name: `Eight of ${W}`, nameKo: '완드의 8', emoji: '🪄', keywords: ['속도', '진행', '이동'], shortReading: '일이 빠르게 진행되거나 움직임이 많은 하루가 될 수 있습니다.', detailedReading: '완드 8은 속도와 진행을 상징합니다. 미룬 일이 있다면 오늘 처리해 보는 것이 좋겠습니다.', advice: '오늘 반드시 하나만 끝내 보세요.', luckyColor: '주황색', luckyNumber: 8 },
  { id: 30, name: `Nine of ${W}`, nameKo: '완드의 9', emoji: '🪄', keywords: ['방어', '끈기', '결의'], shortReading: '어려움이 있어도 끝까지 지켜보는 결의가 도움이 될 수 있습니다.', detailedReading: '완드 9는 끈기와 방어를 상징합니다. 포기하기 직전이라면 한 번만 더 생각해 보세요.', advice: '오늘은 "다음 한 번"만 더 해 보세요.', luckyColor: '빨간색', luckyNumber: 9 },
  { id: 31, name: `Ten of ${W}`, nameKo: '완드의 10', emoji: '🪄', keywords: ['부담', '책임', '완수'], shortReading: '무거운 짐을 느낄 수 있지만, 나누거나 정리하면 가벼워질 수 있습니다.', detailedReading: '완드 10은 부담과 책임을 상징합니다. 혼자 다 짊어지지 말고 도움을 요청해 보는 것도 방법입니다.', advice: '오늘 부담을 하나만 내려놓아 보세요.', luckyColor: '노란색', luckyNumber: 10 },
  { id: 32, name: `Page of ${W}`, nameKo: '완드의 시종', emoji: '🪄', keywords: ['호기심', '소식', '도전'], shortReading: '새로운 소식이나 호기심을 자극하는 일이 있을 수 있습니다.', detailedReading: '완드 시종은 호기심과 새로운 시도를 상징합니다. 모르는 분야를 살짝 알아보는 것도 좋겠습니다.', advice: '오늘 궁금한 것을 하나만 검색해 보세요.', luckyColor: '빨간색', luckyNumber: 11 },
  { id: 33, name: `Knight of ${W}`, nameKo: '완드의 기사', emoji: '🪄', keywords: ['열정', '돌진', '변화'], shortReading: '열정적으로 움직이거나 급한 변화가 있을 수 있는 날입니다.', detailedReading: '완드 기사는 열정과 돌진을 상징합니다. 하고 싶은 일이 있다면 과감히 시작해 보세요. 다만 무리만 하지 않으면 좋겠습니다.', advice: '오늘 한 가지만 과감히 실행해 보세요.', luckyColor: '주황색', luckyNumber: 12 },
  { id: 34, name: `Queen of ${W}`, nameKo: '완드의 여왕', emoji: '🪄', keywords: ['자신감', '리더십', '따뜻함'], shortReading: '당신의 리더십이나 따뜻한 말이 주변에 영향을 줄 수 있는 날입니다.', detailedReading: '완드 여왕은 자신감과 보살핌을 상징합니다. 주변 사람에게 한마디 격려를 건네 보세요.', advice: '오늘 누군가에게 칭찬 한마디를 해 보세요.', luckyColor: '분홍색', luckyNumber: 13 },
  { id: 35, name: `King of ${W}`, nameKo: '완드의 왕', emoji: '🪄', keywords: ['리더십', '결단', '비전'], shortReading: '결단을 내리거나 방향을 제시하는 역할이 잘 맞는 하루입니다.', detailedReading: '완드 왕은 리더십과 비전을 상징합니다. 결정이 필요한 일이 있다면 당신이 먼저 방향을 잡아 보세요.', advice: '오늘 한 가지 결정을 내려 보세요.', luckyColor: '빨간색', luckyNumber: 14 },
  // 컵 (36~49): 감정·관계·직관
  { id: 36, name: `Ace of ${C}`, nameKo: '컵의 에이스', emoji: '🏆', keywords: ['사랑', '새 감정', '직관'], shortReading: '새로운 감정이나 사랑의 에너지가 느껴질 수 있는 날입니다.', detailedReading: '컵 에이스는 새로운 감정과 직관을 상징합니다. 마음이 이끄는 대로 조금만 따라가 보세요.', advice: '오늘 마음이 끌리는 것을 하나만 해 보세요.', luckyColor: '파란색', luckyNumber: 1 },
  { id: 37, name: `Two of ${C}`, nameKo: '컵의 2', emoji: '🏆', keywords: ['파트너십', '조화', '연결'], shortReading: '누군가와의 연결이나 협력이 돋보일 수 있는 하루입니다.', detailedReading: '컵 2는 파트너십과 조화를 상징합니다. 중요한 사람과 대화해 보거나 함께할 시간을 가져 보세요.', advice: '소중한 사람에게 연락 한 통 해 보세요.', luckyColor: '분홍색', luckyNumber: 2 },
  { id: 38, name: `Three of ${C}`, nameKo: '컵의 3', emoji: '🏆', keywords: ['축하', '친교', '즐거움'], shortReading: '친구나 동료와 즐겁게 보내거나 작은 축하가 있을 수 있습니다.', detailedReading: '컵 3는 친교와 축하를 상징합니다. 함께 웃고 이야기하는 시간이 기분을 올려 줄 수 있습니다.', advice: '오늘 누군가와 잠깐이라도 이야기해 보세요.', luckyColor: '초록색', luckyNumber: 3 },
  { id: 39, name: `Four of ${C}`, nameKo: '컵의 4', emoji: '🏆', keywords: ['성찰', '거리두기', '내면'], shortReading: '잠시 혼자만의 시간을 갖거나 감정을 정리해 보는 것이 좋겠습니다.', detailedReading: '컵 4는 성찰과 거리두기를 상징합니다. 무리해서 만나지 않아도 괜찮은 날입니다.', advice: '오늘은 혼자만의 시간을 조금 가져 보세요.', luckyColor: '남색', luckyNumber: 4 },
  { id: 40, name: `Five of ${C}`, nameKo: '컵의 5', emoji: '🏆', keywords: ['상실', '슬픔', '수용'], shortReading: '슬픔이나 아쉬움이 느껴질 수 있지만, 조금씩 수용해 나갈 수 있습니다.', detailedReading: '컵 5는 상실과 슬픔을 상징합니다. 무너진 것만 보지 말고 남아 있는 것도 돌아보세요.', advice: '오늘 아쉬운 것 하나를 적어 보세요.', luckyColor: '회색', luckyNumber: 5 },
  { id: 41, name: `Six of ${C}`, nameKo: '컵의 6', emoji: '🏆', keywords: ['추억', '과거', '순수'], shortReading: '과거의 좋은 추억이나 어린 시절이 떠오를 수 있는 날입니다.', detailedReading: '컵 6은 추억과 순수를 상징합니다. 옛날 이야기를 나누거나 추억을 떠올려 보는 것도 좋겠습니다.', advice: '오늘 좋았던 기억 하나를 떠올려 보세요.', luckyColor: '하늘색', luckyNumber: 6 },
  { id: 42, name: `Seven of ${C}`, nameKo: '컵의 7', emoji: '🏆', keywords: ['선택', '환상', '상상'], shortReading: '많은 선택지가 있어 혼란스러울 수 있지만, 하나씩 걸러 보세요.', detailedReading: '컵 7은 선택과 상상을 상징합니다. 현실과 상상을 구분해 보는 것이 도움이 될 수 있습니다.', advice: '오늘 선택지를 세 개 이하로 줄여 보세요.', luckyColor: '보라색', luckyNumber: 7 },
  { id: 43, name: `Eight of ${C}`, nameKo: '컵의 8', emoji: '🏆', keywords: ['이동', '포기', '새 길'], shortReading: '무언가를 내려놓고 새로운 길로 나서는 에너지가 있을 수 있습니다.', detailedReading: '컵 8은 이별과 새 시작을 상징합니다. 더 이상 맞지 않는 것을 정리해 보는 것도 용기가 됩니다.', advice: '오늘 하나만 내려놓아도 괜찮다고 허락해 보세요.', luckyColor: '파란색', luckyNumber: 8 },
  { id: 44, name: `Nine of ${C}`, nameKo: '컵의 9', emoji: '🏆', keywords: ['만족', '풍요', '감사'], shortReading: '만족스럽고 풍요로운 하루가 될 수 있습니다. 감사해 보세요.', detailedReading: '컵 9는 만족과 풍요를 상징합니다. 가진 것에 감사하는 시간을 가져 보세요.', advice: '오늘 감사한 것 세 가지를 적어 보세요.', luckyColor: '초록색', luckyNumber: 9 },
  { id: 45, name: `Ten of ${C}`, nameKo: '컵의 10', emoji: '🏆', keywords: ['행복', '가족', '완성'], shortReading: '가까운 사람들과의 행복이나 관계의 안정이 느껴질 수 있습니다.', detailedReading: '컵 10은 행복과 완성을 상징합니다. 가족이나 친구와의 시간이 특별할 수 있는 날입니다.', advice: '오늘 소중한 사람에게 감사하다고 말해 보세요.', luckyColor: '분홍색', luckyNumber: 10 },
  { id: 46, name: `Page of ${C}`, nameKo: '컵의 시종', emoji: '🏆', keywords: ['감성', '직관', '소식'], shortReading: '감성적인 소식이나 직관이 맞을 수 있는 날입니다.', detailedReading: '컵 시종은 감성과 직관을 상징합니다. 마음이 끌리는 것을 따라가 보세요.', advice: '오늘 꿈이나 느낌을 한 줄 적어 보세요.', luckyColor: '하늘색', luckyNumber: 11 },
  { id: 47, name: `Knight of ${C}`, nameKo: '컵의 기사', emoji: '🏆', keywords: ['로맨스', '제안', '이상'], shortReading: '로맨틱한 분위기나 좋은 제안이 찾아올 수 있습니다.', detailedReading: '컵 기사는 로맨스와 이상을 상징합니다. 마음을 열고 받아들이는 것이 좋겠습니다.', advice: '오늘 한 가지 제안을 받아들여 보세요.', luckyColor: '파란색', luckyNumber: 12 },
  { id: 48, name: `Queen of ${C}`, nameKo: '컵의 여왕', emoji: '🏆', keywords: ['공감', '감성', '돌봄'], shortReading: '공감과 돌봄이 필요한 사람에게 당신이 힘이 될 수 있는 날입니다.', detailedReading: '컵 여왕은 공감과 감성을 상징합니다. 주변의 감정에 귀 기울여 보세요.', advice: '오늘 누군가의 이야기를 끝까지 들어 보세요.', luckyColor: '분홍색', luckyNumber: 13 },
  { id: 49, name: `King of ${C}`, nameKo: '컵의 왕', emoji: '🏆', keywords: ['감정 리더', '균형', '지원'], shortReading: '감정을 다스리거나 다른 사람을 지원하는 역할이 잘 맞는 하루입니다.', detailedReading: '컵 왕은 감정의 균형과 지원을 상징합니다. 차분하게 상황을 보는 눈이 빛날 수 있습니다.', advice: '오늘 감정이 올라와도 한 번만 멈추고 생각해 보세요.', luckyColor: '파란색', luckyNumber: 14 },
  // 검 (50~63): 사고·갈등·진실
  { id: 50, name: `Ace of ${S}`, nameKo: '검의 에이스', emoji: '⚔️', keywords: ['통찰', '진실', '돌파'], shortReading: '새로운 통찰이나 진실이 밝혀질 수 있는 날입니다.', detailedReading: '검 에이스는 통찰과 돌파를 상징합니다. 막혀 있던 문제의 실마리가 보일 수 있습니다.', advice: '오늘 한 가지 질문에 솔직하게 답해 보세요.', luckyColor: '흰색', luckyNumber: 1 },
  { id: 51, name: `Two of ${S}`, nameKo: '검의 2', emoji: '⚔️', keywords: ['결정 유예', '갈등', '균형'], shortReading: '결정을 미루거나 양쪽 사이에서 고민이 있을 수 있습니다.', detailedReading: '검 2는 갈등과 균형을 상징합니다. 당장 결론을 내리지 않아도 괜찮은 날입니다.', advice: '오늘은 결정을 내리지 않고 정보만 모아 보세요.', luckyColor: '회색', luckyNumber: 2 },
  { id: 52, name: `Three of ${S}`, nameKo: '검의 3', emoji: '⚔️', keywords: ['상처', '슬픔', '치유'], shortReading: '마음의 상처가 느껴질 수 있지만, 인정하는 것만으로도 치유가 시작될 수 있습니다.', detailedReading: '검 3는 상처와 슬픔을 상징합니다. 아픔을 무시하지 말고 조금씩 받아들여 보세요.', advice: '오늘 아픈 감정을 한 줄이라도 적어 보세요.', luckyColor: '남색', luckyNumber: 3 },
  { id: 53, name: `Four of ${S}`, nameKo: '검의 4', emoji: '⚔️', keywords: ['휴식', '회복', '잠시 멈춤'], shortReading: '잠시 멈추고 회복하는 것이 좋은 하루입니다.', detailedReading: '검 4는 휴식과 회복을 상징합니다. 무리하지 말고 몸과 마음을 쉬게 해 보세요.', advice: '오늘은 아무 결정도 하지 않는 날로 삼아 보세요.', luckyColor: '회색', luckyNumber: 4 },
  { id: 54, name: `Five of ${S}`, nameKo: '검의 5', emoji: '⚔️', keywords: ['갈등', '경쟁', '대립'], shortReading: '의견 충돌이나 경쟁이 있을 수 있지만, 감정을 낮추면 풀릴 수 있습니다.', detailedReading: '검 5는 갈등과 대립을 상징합니다. 이기려 하기보다 이해하려 해 보세요.', advice: '오늘은 맞서지 말고 한 발 물러서 보세요.', luckyColor: '검정', luckyNumber: 5 },
  { id: 55, name: `Six of ${S}`, nameKo: '검의 6', emoji: '⚔️', keywords: ['이동', '변화', '새 환경'], shortReading: '어려운 상황에서 벗어나거나 새로운 환경으로 나아갈 수 있는 에너지가 있습니다.', detailedReading: '검 6는 이동과 변화를 상징합니다. 과거를 정리하고 다음 단계로 나아가는 것이 좋겠습니다.', advice: '오늘 하나만 정리하고 넘어가 보세요.', luckyColor: '하늘색', luckyNumber: 6 },
  { id: 56, name: `Seven of ${S}`, nameKo: '검의 7', emoji: '⚔️', keywords: ['전략', '회피', '신중'], shortReading: '신중하게 움직이거나 전략을 세워 보는 것이 좋은 하루입니다.', detailedReading: '검 7은 전략과 신중함을 상징합니다. 직진보다 돌아가는 것이 나을 수 있는 날입니다.', advice: '오늘은 충동적으로 말하지 말고 한 번 생각해 보세요.', luckyColor: '회색', luckyNumber: 7 },
  { id: 57, name: `Eight of ${S}`, nameKo: '검의 8', emoji: '⚔️', keywords: ['제한', '걱정', '탈출'], shortReading: '막혀 있다고 느껴질 수 있지만, 시야를 바꾸면 길이 보일 수 있습니다.', detailedReading: '검 8은 제한과 걱정을 상징합니다. 생각이 반복되면 몸을 움직여 보세요.', advice: '오늘 걱정을 5분만 하고 그만 두세요.', luckyColor: '남색', luckyNumber: 8 },
  { id: 58, name: `Nine of ${S}`, nameKo: '검의 9', emoji: '⚔️', keywords: ['불안', '우울', '밤'], shortReading: '불안이나 우울함이 느껴질 수 있지만, 밤이 지나면 나아질 수 있습니다.', detailedReading: '검 9는 불안과 우울을 상징합니다. 혼자 가라앉지 않는다면 믿는 사람에게 연락해 보세요.', advice: '오늘 힘들면 누군가에게 "심심해"라고만 말해 보세요.', luckyColor: '검정', luckyNumber: 9 },
  { id: 59, name: `Ten of ${S}`, nameKo: '검의 10', emoji: '⚔️', keywords: ['끝', '해방', '새 시작'], shortReading: '어려운 국면이 끝나고 해방감이 올 수 있는 날입니다.', detailedReading: '검 10은 끝과 새 시작을 상징합니다. 가장 어두운 순간이 지나면 조금씩 나아질 수 있습니다.', advice: '오늘 "끝났다"고 한 번 말해 보세요.', luckyColor: '흰색', luckyNumber: 10 },
  { id: 60, name: `Page of ${S}`, nameKo: '검의 시종', emoji: '⚔️', keywords: ['호기심', '정보', '경계'], shortReading: '새로운 정보에 주의를 기울이거나 호기심이 생길 수 있습니다.', detailedReading: '검 시종은 호기심과 정보를 상징합니다. 소문이나 말을 그대로 믿기 전에 확인해 보세요.', advice: '오늘 들어온 소식 하나를 확인해 보세요.', luckyColor: '회색', luckyNumber: 11 },
  { id: 61, name: `Knight of ${S}`, nameKo: '검의 기사', emoji: '⚔️', keywords: ['돌진', '결단', '급함'], shortReading: '급하게 움직이거나 결단이 필요할 수 있지만, 한 번만 멈춰 보세요.', detailedReading: '검 기사는 돌진과 결단을 상징합니다. 속도보다 방향이 맞는지 점검해 보는 것이 좋겠습니다.', advice: '오늘 중요한 말을 하기 전에 3초만 멈춰 보세요.', luckyColor: '검정', luckyNumber: 12 },
  { id: 62, name: `Queen of ${S}`, nameKo: '검의 여왕', emoji: '⚔️', keywords: ['독립', '통찰', '냉정'], shortReading: '냉정하게 판단하거나 독립적으로 행동하는 것이 잘 맞는 하루입니다.', detailedReading: '검 여왕은 통찰과 독립을 상징합니다. 감정에 휩쓸리지 않고 사실을 보는 눈이 빛날 수 있습니다.', advice: '오늘 한 가지를 객관적으로만 바라보세요.', luckyColor: '회색', luckyNumber: 13 },
  { id: 63, name: `King of ${S}`, nameKo: '검의 왕', emoji: '⚔️', keywords: ['권위', '진실', '결단'], shortReading: '진실을 말하거나 권위 있는 결정을 내리는 역할이 맞을 수 있습니다.', detailedReading: '검 왕은 권위와 진실을 상징합니다. 공정하게 판단하는 모습이 주변에 신뢰를 줄 수 있습니다.', advice: '오늘 한 가지에 대해 솔직한 의견을 말해 보세요.', luckyColor: '검정', luckyNumber: 14 },
  // 펜타클 (64~77): 물질·일·안정
  { id: 64, name: `Ace of ${P}`, nameKo: '펜타클의 에이스', emoji: '🪙', keywords: ['풍요', '기회', '새 시작'], shortReading: '물질적이거나 일과 관련된 좋은 기회가 올 수 있는 날입니다.', detailedReading: '펜타클 에이스는 풍요와 새 시작을 상징합니다. 작은 수입이나 제안이 생길 수 있으니 눈을 떠 보세요.', advice: '오늘 들어오는 제안 하나를 진지하게 검토해 보세요.', luckyColor: '금색', luckyNumber: 1 },
  { id: 65, name: `Two of ${P}`, nameKo: '펜타클의 2', emoji: '🪙', keywords: ['균형', '저글링', '조율'], shortReading: '여러 일을 균형 있게 돌려가며 조율해 보는 하루가 좋겠습니다.', detailedReading: '펜타클 2는 균형과 조율을 상징합니다. 한쪽에만 치우치지 않도록 순서를 정해 보세요.', advice: '오늘 할 일 순서를 세 개만 정해 보세요.', luckyColor: '녹색', luckyNumber: 2 },
  { id: 66, name: `Three of ${P}`, nameKo: '펜타클의 3', emoji: '🪙', keywords: ['협력', '기술', '성장'], shortReading: '함께 일하거나 기술을 나누는 것이 돋보일 수 있는 날입니다.', detailedReading: '펜타클 3는 협력과 기술을 상징합니다. 팀으로 일하거나 배우는 것이 좋은 에너지를 만들 수 있습니다.', advice: '오늘 누군가에게 한 가지를 배워 보세요.', luckyColor: '갈색', luckyNumber: 3 },
  { id: 67, name: `Four of ${P}`, nameKo: '펜타클의 4', emoji: '🪙', keywords: ['안정', '저축', '보호'], shortReading: '안정을 유지하거나 소중한 것을 지키는 하루가 좋겠습니다.', detailedReading: '펜타클 4는 안정과 보호를 상징합니다. 무리한 지출보다 지키는 것이 맞을 수 있는 날입니다.', advice: '오늘 꼭 필요한 것만 쓰도록 정해 보세요.', luckyColor: '녹색', luckyNumber: 4 },
  { id: 68, name: `Five of ${P}`, nameKo: '펜타클의 5', emoji: '🪙', keywords: ['어려움', '결핍', '연대'], shortReading: '물질적이거나 일상적인 어려움이 느껴질 수 있지만, 도움을 청해도 됩니다.', detailedReading: '펜타클 5는 결핍과 연대를 상징합니다. 혼자 견디지 말고 주변에 손을 내미는 것도 용기입니다.', advice: '오늘 도움이 필요하면 한 사람에게만 말해 보세요.', luckyColor: '회색', luckyNumber: 5 },
  { id: 69, name: `Six of ${P}`, nameKo: '펜타클의 6', emoji: '🪙', keywords: ['나눔', '기부', '균형'], shortReading: '나누거나 베풀면 좋은 에너지가 돌아올 수 있는 날입니다.', detailedReading: '펜타클 6은 나눔과 균형을 상징합니다. 받기만 하지 말고 줄 수 있는 것이 있다면 나눠 보세요.', advice: '오늘 작은 것이라도 하나 나눠 보세요.', luckyColor: '금색', luckyNumber: 6 },
  { id: 70, name: `Seven of ${P}`, nameKo: '펜타클의 7', emoji: '🪙', keywords: ['인내', '장기', '투자'], shortReading: '결과가 바로 나오지 않아도 인내하며 기다려 보는 하루가 좋겠습니다.', detailedReading: '펜타클 7은 인내와 장기 투자를 상징합니다. 지금의 노력이 나중에 결실을 맺을 수 있습니다.', advice: '오늘 한 가지만 꾸준히 이어가 보세요.', luckyColor: '녹색', luckyNumber: 7 },
  { id: 71, name: `Eight of ${P}`, nameKo: '펜타클의 8', emoji: '🪙', keywords: ['숙련', '연습', '집중'], shortReading: '기술을 갈고닦거나 한 가지에 집중하는 것이 잘 맞는 날입니다.', detailedReading: '펜타클 8은 숙련과 연습을 상징합니다. 반복하는 것이 실력을 올려 줄 수 있습니다.', advice: '오늘 같은 일을 10분만 더 해 보세요.', luckyColor: '갈색', luckyNumber: 8 },
  { id: 72, name: `Nine of ${P}`, nameKo: '펜타클의 9', emoji: '🪙', keywords: ['풍요', '안정', '여유'], shortReading: '물질적이거나 심리적으로 여유가 느껴질 수 있는 날입니다.', detailedReading: '펜타클 9는 풍요와 안정을 상징합니다. 가진 것에 만족하는 시간을 가져 보세요.', advice: '오늘 가진 것 중 하나를 떠올려 감사해 보세요.', luckyColor: '금색', luckyNumber: 9 },
  { id: 73, name: `Ten of ${P}`, nameKo: '펜타클의 10', emoji: '🪙', keywords: ['가족', '유산', '안정'], shortReading: '가족이나 집, 장기적인 안정이 중요한 하루일 수 있습니다.', detailedReading: '펜타클 10은 가족과 유산을 상징합니다. 뿌리 내린 것들을 돌아보는 것이 좋겠습니다.', advice: '오늘 집이나 가족에 대해 한 가지만 생각해 보세요.', luckyColor: '녹색', luckyNumber: 10 },
  { id: 74, name: `Page of ${P}`, nameKo: '펜타클의 시종', emoji: '🪙', keywords: ['학습', '소식', '가능성'], shortReading: '배우거나 새로운 소식이 올 수 있는 날입니다.', detailedReading: '펜타클 시종은 학습과 가능성을 상징합니다. 새로운 공부나 정보에 열려 보세요.', advice: '오늘 모르는 것 하나를 검색해 보세요.', luckyColor: '갈색', luckyNumber: 11 },
  { id: 75, name: `Knight of ${P}`, nameKo: '펜타클의 기사', emoji: '🪙', keywords: ['성실', '안정', '진행'], shortReading: '꾸준하고 성실하게 진행하는 것이 좋은 하루입니다.', detailedReading: '펜타클 기사는 성실과 안정을 상징합니다. 화려하지 않아도 한 걸음씩 나아가 보세요.', advice: '오늘 할 일 하나를 끝까지 해 보세요.', luckyColor: '녹색', luckyNumber: 12 },
  { id: 76, name: `Queen of ${P}`, nameKo: '펜타클의 여왕', emoji: '🪙', keywords: ['풍요', '돌봄', '실용'], shortReading: '실용적으로 돌보거나 풍요를 나누는 역할이 잘 맞는 날입니다.', detailedReading: '펜타클 여왕은 풍요와 돌봄을 상징합니다. 주변을 챙기는 당신의 손이 빛날 수 있습니다.', advice: '오늘 누군가를 위한 작은 것을 하나 해 보세요.', luckyColor: '금색', luckyNumber: 13 },
  { id: 77, name: `King of ${P}`, nameKo: '펜타클의 왕', emoji: '🪙', keywords: ['성공', '안정', '리더십'], shortReading: '물질적이거나 일에서 리더십을 발휘하기 좋은 하루입니다.', detailedReading: '펜타클 왕은 성공과 안정을 상징합니다. 신뢰를 바탕으로 결정을 내리는 것이 좋겠습니다.', advice: '오늘 한 가지 일을 책임지고 마무리해 보세요.', luckyColor: '녹색', luckyNumber: 14 },
];

export const minorArcanaCards: TarotCard[] = minorArcanaCardsBase.map((c) => ({
  ...c,
  imageUrl: `/tarot/${c.id}.jpg`,
}));